name: build-push-image

on:
  - push
  - pull_request
  
jobs:
  push_to_registry:
    name: Build and push the Docker image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/madpoly-studio/aws-s3-reverse-proxy:latest